name: Deploy After Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Run deploy script
        id: deploy_script
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh $BRANCH_NAME

      - name: Add comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          output="${{ steps.deploy_script.outputs.output }}"
          echo "Adding comment: $output"
          gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "$output"
