name: Deploy After Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_linux_amd64.tar.gz -o ghcli.tar.gz
          tar xzf ghcli.tar.gz
          sudo mv gh_2.29.0_linux_amd64/bin/gh /usr/local/bin/
          rm -rf gh_2.29.0_linux_amd64 ghcli.tar.gz

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Install Salesforce DX
        run: |
          echo "Installing Salesforce DX CLI"
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          sudo ./sfdx-cli/install
          echo 'export PATH="$PATH:/opt/sfdx/bin"' >> $HOME/.bash_profile
          source $HOME/.bash_profile
          sfdx --version

      - name: Run deploy script
        id: deploy_script
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh $BRANCH_NAME

      - name: Add comment
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          output="${{ steps.deploy_script.outputs.output }}"
          gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "$output"
